export const POSTS_REQUEST = "POSTS_REQUEST";
export const POSTS_SUCCESS = "POSTS_SUCCESS";
export const POSTS_FAIL = "POSTS_FAIL";

export const SINGLEPOST_REQUEST = "SINGLEPOST_REQUEST";
export const SINGLEPOST_SUCCESS = "SINGLEPOST_SUCCESS";
export const SINGLEPOST_FAIL = "SINGLEPOST_FAIL";

export const ADDPOSTS_REQUEST = "ADDPOSTS_REQUEST";
export const ADDPOSTS_SUCCESS = "ADDPOSTS_SUCCESS";
export const ADDPOSTS_FAIL = "ADDPOSTS_FAIL";

export const DELETE_REQUEST = "DELETE_REQUEST";
export const DELETE_SUCCESS = "DELETE_SUCCESS";
export const DELETE_FAIL = "DELETE_FAIL";
