export const POSTS_REQUEST = "POSTS_REQUEST";
export const POSTS_SUCCESS = "POSTS_SUCCESS";
export const POSTS_FAIL = "POSTS_FAIL";

export const SINGLEPOST_REQUEST = "SINGLEPOST_REQUEST";
export const SINGLEPOST_SUCCESS = "SINGLEPOST_SUCCESS";
export const SINGLEPOST_FAIL = "SINGLEPOST_FAIL";
